[tool.setuptools]
    packages = ["etimer"]
    package-dir = {"" = "src"}

[project]
    name = "etimer"
    version = "2024.11.5"
    description = "Консольный таймер"
    authors = [
        {name="Pavel Bass", email="basspv@vk.com"},
    ]
    readme="README.md"
    
